### ISSUE TITLE
idea: add exif data to each photo

### ISSUE THREAD

**Issue by dcparker88** [parker-camera/parker-camera.github.io#1]
each photo could show something like
* location
* camera settings

i bet there is a ruby gem out there we can use for this.

**Comment by parker2351** [comment]
Create Logo - to be used in top left (and favicon)
Add Chicago pictures
Ensure each photo on main picture page is same size

**Comment by dcparker88** [comment]
started an exif branch. can't figure out some of the liquid passing right now, unfortunately

**Comment by dcparker88** [comment]
we can't use custom ruby gems in github pages. if we wanted to use exif data or other things we'd need to upload to our hosting like heroku or digital ocean. or, we could run from our apartment 😂
